services:
  llm_host:
    image: my/llmimg:v0             # reuse your CUDA-enabled dev image
    container_name: llm_host
    working_dir: /workspace
    stdin_open: true
    tty: true
    init: true
    volumes:
      - ./:/workspace                    # your project code (hot-reload/dev)
      - /mnt/c/Users/icymi/.lmstudio/models:/models:ro  # models (ro is fine)
    environment:
      # Talk to services by Docker DNS name on internal network:
      LLAMACPP_BASE_URL: "http://llama:8001"
      CHROMA_PERSIST_ROOT: "/data/agents"
      HOST: "0.0.0.0"
      PORT: "8080"
      LD_LIBRARY_PATH: "/llama.cpp/build/bin:${LD_LIBRARY_PATH}"
    # Expose the wrapper to localhost:8888 only (not the whole host):
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - llama
      - mcp_duckduckgo
    command: >
      bash -lc "uvicorn agent_host.app.main:app --host 0.0.0.0 --port 8080 --reload"
    networks: [ llmnet ]
    # llm_host itself doesn't need GPU; remove if you prefer:
    # gpus: all

  # === llama.cpp server (internal-only) ===
  llama:
    image: my/llmimg:v0              # use your image that already has CUDA + built llama-server
    container_name: llama
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - /mnt/c/Users/icymi/.lmstudio/models:/models:ro
      - ./cache:/cache                   # for slot/prompt-cache persistence
      - /mnt/c/proj/mcp/hostage/llama.cpp:/llama.cpp:ro  # llama.cpp source (for rebuilds)
    environment:
      LD_LIBRARY_PATH: "/llama.cpp/build/bin:${LD_LIBRARY_PATH}"
    # modern compose GPU flag:
    gpus: all
    # Internal-only service: use expose (no host published port)
    expose:
      - "8001"
    ports:
      - "127.0.0.1:8001:8001"
    command: >
      bash -lc "/llama.cpp/build/bin/llama-server
      --model /models/lmstudio-community/gemma-3-12b-it-GGUF/gemma-3-12b-it-Q4_K_M.gguf
      --mmproj /models/lmstudio-community/gemma-3-12b-it-GGUF/mmproj-model-f16.gguf
      --host 0.0.0.0 --port 8001
      --ctx-size 8192
      --n-gpu-layers 999
      --flash-attn on
      --slot-save-path /cache/slots
      --metrics"
    networks: [ llmnet ]

  # === MCP DuckDuckGo server ===
  mcp_duckduckgo:
    image: mcp/duckduckgo:latest
    container_name: mcp_duckduckgo
    expose:
      - "7801"                            # internal port
    # Publish to localhost only for security:
    networks: [ llmnet ]

networks:
  llmnet:
    driver: bridge